.PHONY: clean All

All:
	@echo "----------Building project:[ delay_5_3 - Debug ]----------"
	@cd "delay_5_3" && "$(MAKE)" -f  "delay_5_3.mk" && "$(MAKE)" -f  "delay_5_3.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ delay_5_3 - Debug ]----------"
	@cd "delay_5_3" && "$(MAKE)" -f  "delay_5_3.mk" clean
