.PHONY: clean All

All:
	@echo "----------Building project:[ interruptions_and_exceptions - Debug ]----------"
	@cd "interruptions_and_exceptions" && "$(MAKE)" -f  "interruptions_and_exceptions.mk" && "$(MAKE)" -f  "interruptions_and_exceptions.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ interruptions_and_exceptions - Debug ]----------"
	@cd "interruptions_and_exceptions" && "$(MAKE)" -f  "interruptions_and_exceptions.mk" clean
