.PHONY: clean All

All:
	@echo "----------Building project:[ spoopys_bizarre_adventure - Debug ]----------"
	@cd "spoopys_bizarre_adventure" && "$(MAKE)" -f  "spoopys_bizarre_adventure.mk" && "$(MAKE)" -f  "spoopys_bizarre_adventure.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ spoopys_bizarre_adventure - Debug ]----------"
	@cd "spoopys_bizarre_adventure" && "$(MAKE)" -f  "spoopys_bizarre_adventure.mk" clean
