.PHONY: clean All

All:
	@echo "----------Building project:[ keypad - Debug ]----------"
	@cd "keypad" && "$(MAKE)" -f  "keypad.mk" && "$(MAKE)" -f  "keypad.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ keypad - Debug ]----------"
	@cd "keypad" && "$(MAKE)" -f  "keypad.mk" clean
